# Generated by Django 4.1 on 2022-08-24 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complimentapi', '0003_alter_receiver_user_compliment'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliment',
            name='last_retrieved_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 7, 31, 8, 249521)),
        ),
    ]
